name: ihopespatial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - git+https://github.com/prabhakarlab/Banksy_py.git
  - scanpy
  - numba
  - llvmlite
  - pandas
  - scipy
  - scikit-learn
  - notebook
  - leidenalg
  - python-igraph
  - h5py
  - anndata
