name: ihopespatial
channels:
  - defaults
dependencies:
  - python=3.10
  - scanpy
  - numba
  - llvmlite
  - pandas
  - scipy
  - scikit-learn
  - notebook
  - leidenalg
  - python-igraph
  - h5py
  - anndata
